---
  elasticsearch:
    hosts:
      elasticsearch:
        ansible_connection: ssh
        ansible_user: root
  kibana:
    hosts:
      elasticsearch:
        ansible_connection: ssh
        ansible_user: root
